org.gradle.jvmargs=-Xmx4096m
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=false
android.useAndroidX=true
android.enableJetifier=false
kotlin.incremental=true
kotlin.incremental.js=true
android.lint.disable=MissingDimensionActivityClassManifest
android.suppressUnsupportedCompileSdk=34
kotlin.gradle.plugin.useK2=false
