#!/usr/bin/env bash
set -euo pipefail

SKILLS_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ROOT_DIR="$(cd "$SKILLS_DIR/.." && pwd)"

agents_path_for_scope() {
  local scope="$1"
  case "$scope" in
    shared) echo "$ROOT_DIR/shared/AGENTS.md" ;;
    composeApp) echo "$ROOT_DIR/composeApp/AGENTS.md" ;;
    skills) echo "$ROOT_DIR/skills/AGENTS.md" ;;
    *) echo "$ROOT_DIR/AGENTS.md" ;;
  esac
}

echo "Syncing skills from $SKILLS_DIR"

synced=0
warned=0

for skill_file in "$SKILLS_DIR"/*/SKILL.md; do
  skill_dir=$(dirname "$skill_file")
  skill_name=$(basename "$skill_dir")

  [[ "$skill_name" == "skill-sync" ]] && continue

  description=$(awk '/^---/{f++} f==1 && /^description:/{gsub(/^description: */,""); print; exit}' "$skill_file")
  scope=$(awk '/^---/{f++} f==1 && /^scope:/{gsub(/^scope: */,""); print; exit}' "$skill_file")

  if [[ -z "$scope" ]]; then
    echo "  warning: $skill_name has no scope"
    ((warned++))
    continue
  fi

  IFS=',' read -ra scope_list <<< "$scope"

  for raw_scope in "${scope_list[@]}"; do
    s=$(echo "$raw_scope" | xargs)
    agents_file=$(agents_path_for_scope "$s")
    agents_dir=$(dirname "$agents_file")

    rel_skill=$(realpath --relative-to="$agents_dir" "$skill_file")
    entry="| \`$skill_name\` | $description | \`$rel_skill\` |"
    marker="<!-- skill-sync:$skill_name -->"

    if [[ ! -f "$agents_file" ]]; then
      mkdir -p "$agents_dir"
      cat > "$agents_file" <<EOF
# AGENTS.md - $(basename "$agents_dir")

> Auto-generated by skill-sync. Edit manually with care.

## Skills

| Skill | Description | File |
|-------|-------------|------|
EOF
    fi

    if grep -q "$marker" "$agents_file" 2>/dev/null; then
      sed -i "/$marker/c\\$entry $marker" "$agents_file"
      echo "  updated [$skill_name] -> $(basename "$agents_file")"
    else
      if grep -q "^|-------|-------------|------|" "$agents_file"; then
        sed -i "/^|-------|-------------|------|/a\\$entry $marker" "$agents_file"
      else
        echo "$entry $marker" >> "$agents_file"
      fi
      echo "  added   [$skill_name] -> $(basename "$agents_file")"
    fi
    ((synced+=1))
  done
done

echo "Synced: $synced"
[[ $warned -gt 0 ]] && echo "Warned: $warned"
