package com.recipecostcalculator.ui.strings.es

object Ingredients {
    val title = "Ingredientes"
    val newIngredient = "Nuevo Ingrediente"
    val editIngredient = "Editar Ingrediente"
    val name = "Nombre"
    val dimension = "Tipo de medida"
    val purchaseUnit = "Unidad de compra"
    val purchasePackageLabel = "Detalles (opcional)"
    val purchasePrice = "Precio pagado por el paquete"
    val purchasePriceHelper = "Lo que pagaste en total por ese paquete"
    val contentAmount = "Contenido del paquete"
    val contentAmountHelper = "Cuánto trae el paquete que compraste"
    val quantity = "Cantidad"
    val usageUnit = "Unidad de uso"
    val unitCost = "Costo por unidad"
    val purchaseSummary = "Pagaste $%s por %s %s"
    val updatePrice = "Actualizar precio"
    val price = "Precio"
    val deleteIngredient = "Eliminar ingrediente"
    val deleteIngredientConfirmation = "¿Eliminar \"%s\"?"
    val noIngredients = "No hay ingredientes. Toca + para agregar."
    val dimensionMass = "Peso"
    val dimensionVolume = "Volumen"
    val dimensionCount = "Unidad"
}
