package com.recipecostcalculator.ui.strings.es

object Ingredients {
    val title = "Ingredientes"
    val newIngredient = "Nuevo Ingrediente"
    val editIngredient = "Editar Ingrediente"
    val name = "Nombre"
    val dimension = "Tipo de medida"
    val purchaseUnit = "Unidad de compra"
    val purchasePackageLabel = "Etiqueta del envase (opcional)"
    val purchasePrice = "Precio de compra"
    val quantity = "Cantidad en envase"
    val usageUnit = "Unidad de uso"
    val unitCost = "Costo por unidad"
    val updatePrice = "Actualizar precio"
    val price = "Precio"
    val deleteIngredient = "Eliminar ingrediente"
    val deleteIngredientConfirmation = "¿Eliminar \"%s\"?"
    val enterValidNumber = "Ingrese un número válido"
    val noIngredients = "No hay ingredientes. Toca + para agregar."
    val perUnit = "por"
    val dimensionMass = "Peso"
    val dimensionVolume = "Volumen"
    val dimensionCount = "Unidad"
}
