package com.recipecostcalculator.ui.strings.es

object Recipes {
    val title = "Recetas"
    val newRecipe = "Nueva Receta"
    val editRecipe = "Editar Receta"
    val recipeName = "Nombre de la receta"
    val parentRecipe = "Receta base"
    val noParentRecipe = "Ninguna"
    val inheritedIngredients = "Ingredientes base"
    val ownIngredients = "Ingredientes propios"
    val deleteIngredient = "Eliminar ingrediente"
    val deleteIngredientFromRecipe = "¿Eliminar este ingrediente de la receta?"
    val noIngredients = "Sin ingredientes - toca aquí para agregar"
    val ingredientCount = "ingredientes"
    val ingredientSingular = "ingrediente"
    val baseRecipeSuffix = "receta base"
    val supplies = "Insumos"
    val fixedCostLine = "Costo fijo"
    val totalCost = "Costo total"
    val includeFixedCosts = "Incluir costos fijos"
    val noRecipes = "No hay recetas. Toca + para crear una."
    val addIngredient = "Agregar Ingrediente"
    val deleteRecipe = "Eliminar receta"
    val deleteRecipeConfirmation = "¿Eliminar la receta \"%s\"? Esta acción no se puede deshacer."
    val yieldModeOption = "Rinde"
    val usageModeOption = "Cantidad"
    val yieldFieldLabel = "Rinde"
    val yieldPlaceholder = "¿Cuántas pizzas rinde?"
    val yieldHelper = "Divide el precio entre las pizzas que rinde"
    val yieldDisplay = "rinde %d pizzas"
}